# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
        pip install pyaudio --user
        sudo apt-get install python-pyaudio
        sudo apt-get install ffmpeg
        sudo apt-get install libav-tools
        sudo pip install pyaudio
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with pytest
      run: |
        pytest
